SD-835: drone file changed to push latest tagged image to repo
UKHomeOffice/modern-slavery-data-service pull request #49
Opened 2021-07-01 12:42 UTC by SarahJaneLuff

**Changes**
- Added imaged tagged server-latest, alerts-latest and lookup-latest to repo, to be used by modern slavery pipeline.

2021-07-01 12:57 UTC, Alex-Swann commented on .drone.yml
> +    - docker push quay.io/ukhomeofficedigital/modern-slavery:server-latest
You don't need to do this. Lines 33-35 are the images you have built which are tagged with <service>-latest. Lines 36-38 will be pushing images that haven't been built so do not exist.

2021-07-01 12:57 UTC, Alex-Swann requested changes
See comment

2021-07-01 13:13 UTC, Alex-Swann commented on .drone.yml
> +    - docker push quay.io/ukhomeofficedigital/modern-slavery:server-latest
Ah I see they are pushing by tag and not image name. Therefore you need line 36-38 to be
```
docker push quay.io/ukhomeofficedigital/modern-slavery-data-service:server-latest
docker push quay.io/ukhomeofficedigital/modern-slavery-data-service:alerts-latest
docker push quay.io/ukhomeofficedigital/modern-slavery-data-service:lookup-latest
```

2021-07-01 14:21 UTC, SarahJaneLuff commented on .drone.yml
> +    - docker push quay.io/ukhomeofficedigital/modern-slavery:server-latest
cools, thanks. Changes these lines.

2021-07-02 10:32 UTC, merged

2021-07-02 10:37 UTC, Alex-Swann reviewed
all good